# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AMoAdDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AMoAdDemo
  pod "AMoAd"

  target 'AMoAdDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AMoAdDemoUITests' do
    # Pods for testing
  end

end
